apiVersion: v1
kind: Pod
metadata:
  name: default-cpu-demo-2
spec:
  containers:
  - name: default-cpu-demo-2-ctr
    image: nginx
    resources:
      limits:
        cpu: "1"


# here in this file we mentioned the limit but not mentioned the request and we know when limit is mentioned then 
#and request is not then limit = request