apiVersion: v1
kind: Pod
metadata:
  name: default-cpu-demo-3
spec:
  containers:
  - name: default-cpu-demo-3-ctr
    image: nginx
    resources:
      requests:
        cpu: "0.75"

#here we mentioned request but not limit and we know that if request is mentioned and limit is not then limit != request

#limit goes the default limit 1