apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default:
      cpu: 1
    defaultRequest:
      cpu: 0.5
    type: Container

    #here in this file we define that you can request for500 milicpu but if you have requiremt for more then 
    # you can take upto 1000